apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-app.mongodbDataPvc" . }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageclass }}