apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-app.mongodbFullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-app.mongodbLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-app.mongodbSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-app.mongodbSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "helm-app.mongodbDataPvc" . }}