replicaCount: 1

namespace: stakefish-app

storageclass: gp3

image:
  repository: dicktangdev/problem-main
  tag: "0.1.0"

service:
  type: ClusterIP
  app_port: 3000
  mongodb_port: 27017

mongodb:
  MONGO_DB: mydatabase
  secretName: mongodb-credentials

