# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_DB
              value: {{ .Values.mongodb.MONGO_DB }}
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: username
            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: password
