apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.app_port }}
      targetPort: {{ .Values.service.app_port }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "helm-app.selectorLabels" . | nindent 4 }}
